# Site Build Settings

# jekyll-paginate configuration


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
plugins:
# - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-mentions
  
include:
  - node_modules
  
# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: "PatrickJr's Virtual Photography"
author: "PatrickJr."
description: 📷
repository: PatrickJnr/vp
github: PatrickJnr/vp

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
# feed:
#   path: rss-feed.xml

jekyll-mentions:
  base_url: https://twitter.com
